// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Day01Input$Bs2018 = require("./Day01Input.bs.js");

var cmp = Caml_obj.caml_compare;

var IntCmp = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

function firstRepeatedFreq(_frequencies, _sumFreq, _acumSum) {
  while(true) {
    var acumSum = _acumSum;
    var sumFreq = _sumFreq;
    var frequencies = _frequencies;
    if (frequencies) {
      var sum = acumSum + frequencies[0] | 0;
      var match = Belt_Set.has(sumFreq, sum);
      if (match) {
        return sum;
      } else {
        _acumSum = sum;
        _sumFreq = Belt_Set.add(sumFreq, sum);
        _frequencies = frequencies[1];
        continue ;
      }
    } else {
      _frequencies = Day01Input$Bs2018.input;
      continue ;
    }
  };
}

var set = Belt_Set.make(IntCmp);

console.log(firstRepeatedFreq(Day01Input$Bs2018.input, set, 0));

var input = Day01Input$Bs2018.input;

exports.IntCmp = IntCmp;
exports.input = input;
exports.firstRepeatedFreq = firstRepeatedFreq;
exports.set = set;
/* IntCmp Not a pure module */
