// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Day01Input$Bs2018 = require("./Day01Input.bs.js");

function calcFinalFrequency(input) {
  if (input) {
    return input[0] + calcFinalFrequency(input[1]) | 0;
  } else {
    return 0;
  }
}

console.log(calcFinalFrequency(Day01Input$Bs2018.input));

exports.calcFinalFrequency = calcFinalFrequency;
/*  Not a pure module */
